2025-10-14 15:36:49,864 INFO     Running data_generator_swes.py
2025-10-14 15:36:51,411 ERROR    Gusto is logging this unhandled exception:
Traceback (most recent call last):
  File "/home/katie795/NeuralPDE_workspace/NeuralPDE/src/data_generator_swes.py", line 98, in <module>
    dataset.prepare_for_model()
  File "/home/katie795/NeuralPDE_workspace/NeuralPDE/src/neural_pde/datasets.py", line 500, in prepare_for_model
    p2.apply(h1, h_inp)
  File "/home/katie795/NeuralPDE_workspace/NeuralPDE/src/neural_pde/datasets.py", line 341, in apply
    u.assign(self._v)
  File "petsc4py/PETSc/Log.pyx", line 250, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 251, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/katie795/software/venv-firedrake/lib/python3.12/site-packages/firedrake/adjoint_utils/function.py", line 116, in wrapper
    ret = assign(self, other, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie795/software/venv-firedrake/lib/python3.12/site-packages/firedrake/function.py", line 461, in assign
    Assigner(self, expr, subset).assign()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie795/software/venv-firedrake/lib/python3.12/site-packages/firedrake/assign.py", line 155, in __init__
    raise ValueError("All functions in the expression must use the same "
ValueError: All functions in the expression must use the same mesh as the assignee
