2025-10-23 10:25:05,990 INFO     Running data_generator_swes.py --filename data/data_test_swes_nref_3_10.h5 --nref 3 --omega 1e-4 --g 9.8 --nt 1000 --tfinalmax 10 --nsamples 128 --t_interval 50 --t_sigma 25 --t_lowest 800 --t_highest 1000
2025-10-23 10:25:06,366 ERROR    Gusto is logging this unhandled exception:
Traceback (most recent call last):
  File "/home/katie795/NeuralPDE_workspace/NeuralPDE/src/data_generator_swes.py", line 148, in <module>
    dataset.prepare_for_model()
  File "/home/katie795/NeuralPDE_workspace/NeuralPDE/src/neural_pde/datasets.py", line 520, in prepare_for_model
    vort1 = netCDF4file.variables['RelativeVorticity']
            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'RelativeVorticity'
