2025-10-23 10:27:38,767 INFO     Running plot_data.py --move_to_windows
2025-10-23 10:28:30,812 ERROR    Gusto is logging this unhandled exception:
Traceback (most recent call last):
  File "/home/katie795/NeuralPDE_workspace/NeuralPDE/src/plot_data.py", line 122, in <module>
    move_files_and_directories(wsl_folder3, windows_folder)
  File "/home/katie795/NeuralPDE_workspace/NeuralPDE/src/plot_data.py", line 92, in move_files_and_directories
    for item in os.listdir(wsl_folder):
                ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/katie795/NeuralPDE_workspace/NeuralPDE/src/output_for_evaluation/animation'
