2025-10-22 14:50:53,178 INFO     Running data_generator_swes.py --filename data/data_valid_swes_nref_3_10.h5 --nref 3 --omega 1e-4 --g 9.8 --nt 1000 --tfinalmax 10 --nsamples 128 --t_interval 50 --t_sigma 25 --t_lowest 0 --t_highest 800
2025-10-22 14:50:53,502 ERROR    Gusto is logging this unhandled exception:
Traceback (most recent call last):
  File "/home/katie795/NeuralPDE_workspace/NeuralPDE/src/data_generator_swes.py", line 148, in <module>
    dataset.prepare_for_model()
  File "/home/katie795/NeuralPDE_workspace/NeuralPDE/src/neural_pde/datasets.py", line 518, in prepare_for_model
    vort1 = afile.load_function(mesh_h5, 'Divergence', idx=start)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "petsc4py/PETSc/Log.pyx", line 250, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 251, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/katie795/software/venv-firedrake/lib/python3.12/site-packages/firedrake/checkpointing.py", line 1351, in load_function
    raise RuntimeError(f"""
RuntimeError: 
                Function (Divergence) not found under either of the following path in results/output/chkpt.h5:

                topologies/firedrake_mixed_meshes/IcosahedralMesh
                topologies/IcosahedralMesh_topology/firedrake_meshes/IcosahedralMesh
            
