2025-10-23 10:53:40,386 INFO     Running data_generator_swes.py --filename data/data_train_swes_vorticity_nref_5_0.05.h5 --nref 5 --omega 1e-4 --g 9.8 --nt 10 --tfinalmax 0.05 --nsamples 8 --t_interval 10 --t_sigma 5 --t_lowest 0 --t_highest 10
2025-10-23 10:53:42,801 ERROR    Gusto is logging this unhandled exception:
Traceback (most recent call last):
  File "/home/katie795/NeuralPDE_workspace/NeuralPDE/src/data_generator_swes.py", line 148, in <module>
    dataset.prepare_for_model()
  File "/home/katie795/NeuralPDE_workspace/NeuralPDE/src/neural_pde/datasets.py", line 520, in prepare_for_model
    vort1 = netCDF4file.variables['RelativeVorticity']
            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'RelativeVorticity'
