2025-10-21 13:38:42,307 INFO     Running evaluate.py
2025-10-21 13:38:42,379 ERROR    Gusto is logging this unhandled exception:
Traceback (most recent call last):
  File "/home/katie795/NeuralPDE_workspace/NeuralPDE/src/evaluate.py", line 12, in <module>
    from neural_pde.loss_functions import mse_absolute_error as metric
ImportError: cannot import name 'mse_absolute_error' from 'neural_pde.loss_functions' (/home/katie795/NeuralPDE_workspace/NeuralPDE/src/neural_pde/loss_functions.py)
